sonar.projectKey=Med-Aziz-Daira_noteops
sonar.organization=med-aziz-daira
sonar.projectName=NoteOps
sonar.projectVersion=1.0

sonar.sources=backend/app,frontend/src
sonar.tests=backend/tests
sonar.python.coverage.reportPaths=backend/coverage.xml
sonar.python.version=3.12

sonar.exclusions=**/node_modules/**,**/venv/**,**/*.pyc,**/migrations/**
