apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: noteops
type: Opaque
stringData:
  POSTGRES_DB: noteops
  POSTGRES_USER: noteops
  POSTGRES_PASSWORD: noteops
  DATABASE_URL: postgresql://noteops:noteops@postgres-service:5432/noteops
